---
title: "Lukas_data"
author: "Carlos Eduardo Madureira Trufen"
date: "2022-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# Load libraries

```{r}
library(readxl)
library(tictoc)
library(tidyverse)
```

# functions

```{r}
# # form https://stackoverflow.com/questions/12688717/round-up-from-5
# round2 = function(x, digits) {
#   posneg = sign(x)
#   z = abs(x)*10^digits
#   z = z + 0.5 + sqrt(.Machine$double.eps)
#   z = trunc(z)
#   z = z/10^digits
#   z*posneg
# }
```

# function calculate_max

```{r}

file <- "~/PRIMUS/data/18_lab/Kadu/000_PV.csv"
column_map <- read_excel("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/column map 23 with names.xlsx", col_names = FALSE)
column_map <- column_map %>% 
  dplyr::mutate(start_end = rep(c("start", "end"), times = 107)) %>% 
  pivot_wider(names_from = "start_end", values_from = "...1")

col_names_v <- column_map$...3 %>% discard(is.na)
title_v <- column_map$...4 %>% discard(is.na)

calculate_max <- function(file , column_map, n_threads){
  
  library(tidyverse)
  library(furrr)
  
  time_v <- file %>% str_extract(pattern = "[:digit:]{3}")
  type_v <- file %>% str_remove(pattern = ".csv") %>% str_split(pattern = "\\_") %>% .[[1]] %>% .[3]
  
  df <- vroom::vroom(file = file, 
                   delim = ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   skip = 10, 
                   num_threads = 50 
                   )
  df_list = list()
  for (i in seq(from = 1, to = 213, by = 2)){
    df_list[[(i+1)/2]] = df[, column_map$start[i]:column_map$end[i+1]]
    }
  
  df_list <- df_list %>% purrr::set_names(paste0("window_", 1:107))
  
  # df_list$window_1 %>% rowwise() %>% mutate(max = max(c_across(names(.)[1]:names(.)[ncol(.)])))
  
  # df_list <- purrr::map(seq_along(df_list), function(i) {
      # print(i)
  #   df_list[[i]] %>% 
  #     rowwise() %>% 
  #     mutate(max = max(c_across(names(.)[1]:names(.)[ncol(.)])))
  #   }
  #   )
  
    plan(multisession, workers = n_threads)
    df_list <- furrr::future_map(seq_along(df_list), function(i) {
      df_list[[i]] %>% 
        rowwise() %>% 
        mutate(max = max(c_across(names(.)[1]:names(.)[ncol(.)])))
    }
    )

  df_max <- df_list %>% 
    purrr::map(dplyr::select, max) %>% 
    bind_cols()
  
  time_file_df <- data.frame(
    time = rep(time_v, times = nrow(df_max)),
    type = rep(type_v, times = nrow(df_max))
    )

  df_max <- df_max %>% bind_cols(time_file_df)
  
  return(df_max)
}

tic()
df_max <- calculate_max(file = "~/PRIMUS/data/18_lab/Kadu/000_PV.csv", column_map = column_map, n_threads = 50)
toc()

```

# calculate max for all files
```{r}
files_v <- list.files("~/PRIMUS/data/18_lab/Kadu/", pattern = ".csv", full.names = TRUE)

df_max_list <- purrr::map(seq_along(files_v), function(i) {
  print(i) 
  calculate_max(file = files_v[i], column_map = column_map, n_threads = 50)
  }
  )
```

# Combine data

```{r}
df_max_df <- df_max_list %>% bind_rows()
df_max_df <- df_max_df %>% 
  mutate(time = time %>% as.numeric() %>% `/`(10))

df_max_df %>% vroom::vroom_write(file = "~/PRIMUS/data/83_BIOINFORMATICS/Kadu/max_df.csv", delim = ";", num_threads = 50)
df_max_df %>% vroom::vroom_write(file = "~/PRIMUS/data/18_lab/Kadu/max_df.csv", delim = ";", num_threads = 50)
```

# Plot figure

```{r}
df_max_df <- vroom::vroom(file = "~/PRIMUS/data/83_BIOINFORMATICS/Kadu/max_df.csv", delim = ";", num_threads = 50)
# df_max_df <- df_max_df %>% purrr::set_names(col_names_v, time, type)

max_list <- df_max_df %>% 
  pivot_longer(cols = 1:107, names_to = "max", values_to = "n") %>% 
  split(f = .$max)

max_trend_plot_list <- purrr::map(seq_along(max_list), function(i) {
  print(i)
  max_list[[i]] %>% 
    ggplot(aes(x = time, y = n, color = type, fill = type)) +
    geom_smooth(method = "loess", se = FALSE) +
    scale_color_manual(values = c("#000000", "#00ff00", "#044fff", "#ffa500", "#ff0000"),
                        labels = c("CV", "PV", "Z1", "Z2", "Z3")) +
    theme_bw() +
    ggeasy::easy_text_size(size = 20) +
    labs(x = "Time [hours]", y = "Intensity [A.U.]", title = title_v[i])
  })
  
purrr::map(seq_along(max_trend_plot_list), function(i) {
  print(i)
  max_trend_plot_list[[i]] %>% ggsave(file = paste0("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/", title_v[i], ".png"), width = 7, height = 5, dpi = 900)
  })
```

# median
```{r}
median_list <- df_max_df %>% 
  unite(time:type, col = "time_type", sep = "_") %>% 
  split(f = .$time_type) %>% 
  purrr::map(function(x) x %>% 
               dplyr::select(-time_type) %>% 
               t() %>% 
               as.data.frame() %>% 
               rowwise() %>% 
               mutate(median = median(c_across(names(.)[1]:names(.)[ncol(.)]))) 
             )

median_df <- median_list %>% 
  purrr::map(dplyr::select, median) %>% 
  bind_rows(.id = "time_type") %>% 
  separate(col = "time_type", into = c("time", "type"), sep = "_") %>% 
  mutate(max_n = rep(paste0("max_", 1:107), times = 40)) %>% 
  mutate(time = time %>% as.numeric)

# median_df %>% vroom::vroom_write(file = "~/PRIMUS/data/83_BIOINFORMATICS/Kadu/median_df.csv", delim = ";", num_threads = 50)
# median_df %>% vroom::vroom_write(file = "~/PRIMUS/data/18_lab/Kadu/median_df.csv", delim = ";", num_threads = 50) 
median_df <- vroom::vroom(file = "~/PRIMUS/data/83_BIOINFORMATICS/Kadu/median_df.csv", delim = ";", num_threads = 50)

median_data_to_plot <- median_df %>% 
  mutate(compund_n = max_n %>% str_remove(pattern = "max\\_") %>% as.numeric()) %>% 
  arrange(compund_n) %>% 
  split(f = .$compund_n)

median_data_to_plot <- median_data_to_plot %>% purrr::set_names(title_v)
median_df <- median_data_to_plot %>% bind_rows(.id = "compound")
# median_df %>% vroom::vroom_write(file = "~/PRIMUS/data/18_lab/Kadu/median_df.csv", delim = ";", num_threads = 50)
# median_df %>% vroom::vroom_write(file = "~/PRIMUS/data/83_BIOINFORMATICS/Kadu/median_df.csv", delim = ";", num_threads = 50)

i <- 105

median_data_fig_list <- purrr::map(seq_along(median_data_to_plot), function(i) { 
  median_data_to_plot[[i]] %>% 
    arrange(time) %>% 
    ggplot(aes(x = time, y = median, color = type)) +
    # geom_point() +
    geom_line() +
    # geom_smooth(method = "loess", se = FALSE) +
    scale_color_manual(values = c("#000000", "#00ff00", "#044fff", "#ffa500", "#ff0000"),
                        labels = c("CV", "PV", "Z1", "Z2", "Z3")) +
    theme_bw() +
    ggeasy::easy_text_size(size = 20) +
    labs(x = "Time [hours]", y = "Intensity [A.U.]", title = title_v[i])
  })



purrr::map(seq_along(median_data_fig_list), function(i) {
  print(i)
  median_data_fig_list[[i]] %>% ggsave(file = paste0("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/median_", title_v[i], ".png"), width = 7, height = 5, dpi = 900)
  })

purrr::map(seq_along(median_data_fig_list), function(i) {
  print(i)
  median_data_fig_list[[i]] %>% ggsave(file = paste0("~/PRIMUS/data/18_lab/Kadu/Lukas_data/median_", title_v[i], ".png"), width = 7, height = 5, dpi = 900)
  })
```

# Load data
```{r}
df_cv <- vroom::vroom("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/000_CV.csv", 
                   delim = ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   skip = 10, 
                   num_threads = 50 
                   )

# df_cv <- df_cv %>% purrr::set_names(c("m/z" , names(df_cv)[2:ncol(df_cv)] %>% as.numeric() %>% round(digits = 5) %>% as.character()))

df_pv <- vroom::vroom("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/000_PV.csv", 
                   delim = ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   skip = 10, 
                   num_threads = 50 
                   )

df_z1 <- vroom::vroom("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/000_Z1.csv", 
                   delim = ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   skip = 10, 
                   num_threads = 50 
                   )

df_z2 <- vroom::vroom("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/000_Z2.csv", 
                   delim = ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   skip = 10, 
                   num_threads = 50 
                   )

df_z3 <- vroom::vroom("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/000_Z3.csv", 
                   delim = ";", 
                   escape_double = FALSE, 
                   trim_ws = TRUE,
                   skip = 10, 
                   num_threads = 50 
                   )

# df_pv <- df_pv %>% purrr::set_names(c("m/z" , names(df_pv)[2:ncol(df_pv)] %>% as.numeric() %>% round(digits = 5) %>% as.character()))

column_map <- read_excel("~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/column map 2.xlsx", col_names = FALSE)
column_map <- column_map %>% 
  dplyr::mutate(start_end = rep(c("start", "end"), times = 107)) %>% 
  pivot_wider(names_from = "start_end", values_from = "...1")


df_cv_list = list()
for (i in seq(from = 1, to = 213, by = 2)){
  df_cv_list[[(i+1)/2]] = df_cv[, column_map$start[i]:column_map$end[i+1]]
}

df_cv_list <- df_cv_list %>% purrr::set_names(paste0("window_", 1:107))

df_cv_list$window_1 %>% rowwise() %>% mutate(max = max(c_across(names(.)[1]:names(.)[ncol(.)])))

df_cv_list <- purrr::map(seq_along(df_cv_list), function(i) {
  df_cv_list[[i]] %>% 
    rowwise() %>% 
    mutate(max = max(c_across(names(.)[1]:names(.)[ncol(.)])))
  }
)

df_cv_max <- df_cv_list %>% 
  purrr::map(dplyr::select, max) %>% 
  bind_cols() 

time_file_df_cv <- data.frame(
  time = rep("0", times = nrow(df_cv_max)),
  file = rep("CV", times = nrow(df_cv_max))
)

df_cv_max <- df_cv_max %>% bind_cols(time_file_df_cv)  


df_pv_list = list()
for (i in seq(from = 1, to = 213, by = 2)){
  df_pv_list[[(i+1)/2]] = df_pv[, column_map$start[i]:column_map$end[i+1]]
}

df_pv_list <- df_pv_list %>% purrr::set_names(paste0("window_", 1:107))

df_pv_list$window_1 %>% rowwise() %>% mutate(max = max(c_across(names(.)[1]:names(.)[ncol(.)])))

df_pv_list <- purrr::map(seq_along(df_pv_list), function(i) {
  df_pv_list[[i]] %>% 
    rowwise() %>% 
    mutate(max = max(c_across(names(.)[1]:names(.)[ncol(.)])))
  }
)

df_pv_max <- df_pv_list %>% 
  purrr::map(dplyr::select, max) %>% 
  bind_cols() 

time_file_df_pv <- data.frame(
  time = rep("0", times = nrow(df_cv_max)),
  file = rep("PV", times = nrow(df_pv_max))
)

df_pv_max <- df_pv_max %>% bind_cols(time_file_df_pv)  

# merge data
df_max <- bind_rows(df_cv_max, df_pv_max)

df_max %>% vroom::vroom_write(file = "~/PRIMUS/data/83_BIOINFORMATICS/Kadu/Lukas_data/df_max.tsv", delim = ";")
```

```{r}
df_max_list <- purrr::map(1:107, function(i) df_max %>% 
                            dplyr::select(i, m_z, file) 
                          ) %>% 
  purrr::map(purrr::set_names, c("max", "m_z", "file")) %>% 
  purrr::set_names(paste0("max_", 1:107))

hist_fig_list <- purrr::map(seq_along(df_max_list), function(i) df_max_list[[i]] %>% 
  ggplot(aes(x = max, color = file)) +
  geom_density() +
  theme_bw() +
  labs(title = names(df_max_list)[i])
)

df_max_list$max_1

```
